
name: ngrok
adopt-info: ngrok
summary: ngrok secure introspectable tunnels to localhost.
description: |
	An instant, secure tunnel from a public URL to your localhost server through any NAT or firewall.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

parts:
  ngrok:
    plugin: dump
    source:
      - on amd64: https://bin.equinox.io/a/23C61AUP19h/ngrok-2.3.40-linux-amd64.zip
      - on i386: https://bin.equinox.io/a/e1oeYn14gE2/ngrok-2.3.40-linux-386.zip
      - on armhf: https://bin.equinox.io/a/7PweAMhmg2R/ngrok-2.3.40-linux-arm64.zip
      - on arm64: https://bin.equinox.io/a/7PweAMhmg2R/ngrok-2.3.40-linux-arm64.zip
      - on s390x: https://bin.equinox.io/a/8h7y12tuRxC/ngrok-2.3.40-linux-s390x.zip
      - on ppc64el: https://bin.equinox.io/a/6nqEc1UDSka/ngrok-2.3.40-linux-ppc64le.zip
    source-checksum:
      - on amd64: sha256/a3028c933dd419933167ecd1b5f2b8b151a1d14b4b7afcbaaa3fcd5c94c03b3c
      - on i386: sha256/e2c5245293e5cfc2cfeac15d48860afb0cdfa160aa5ee088084760f412098631
      - on armhf: sha256/261918195912466c935ede7cf55605ab0f9658d6fadb0f37f54e715ea1ec2c29
      - on arm64: sha256/261918195912466c935ede7cf55605ab0f9658d6fadb0f37f54e715ea1ec2c29
      - on s390x: sha256/8d7592bcdbb96616d3aeb87c65f4450f935d15fb06e3fcbac41403cb6a064417
      - on ppc64el: sha256/ef6e06db10699e78e052e0deb5ca371cfb4986b64a4157a5758398df0de74033
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(./ngrok --version | cut -d " " -f 3)

plugs:
  ngrok-config:
    interface: personal-files
    write:
    - $HOME/.ngrok2

apps:
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home, ngrok-config]
