
name: ngrok
adopt-info: ngrok
summary: ngrok secure introspectable tunnels to localhost.
description: An instant, secure tunnel from a public URL to your localhost server through any NAT or firewall.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el

parts:
  ngrok:
    plugin: dump
    source:
      - on amd64: https://bin.equinox.io/a/23C61AUP19h/ngrok-2.3.40-linux-amd64.zip
      - on i386: https://bin.equinox.io/a/e1oeYn14gE2/ngrok-2.3.40-linux-386.zip
      - on armhf: https://bin.equinox.io/a/4B1Ra9qfT4E/ngrok-2.3.40-linux-arm.zip
      - on arm64: https://bin.equinox.io/a/7PweAMhmg2R/ngrok-2.3.40-linux-arm64.zip
      - on s390x: https://bin.equinox.io/a/8h7y12tuRxC/ngrok-2.3.40-linux-s390x.zip
      - on ppc64el: https://bin.equinox.io/a/6nqEc1UDSka/ngrok-2.3.40-linux-ppc64le.zip
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(./ngrok --version | cut -d " " -f 3)

plugs:
  ngrok-config:
    interface: personal-files
    write:
    - $HOME/.ngrok2

apps:
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home, ngrok-config]
